CREATE TABLE IF NOT EXISTS MOVIE(
  ID             VARCHAR2(50 CHAR) NOT NULL
, TITLE          VARCHAR2(200 CHAR) NOT NULL
, RATING         NUMBER(18) NOT NULL
, RELEASEDATE    VARCHAR2(30 CHAR) NOT NULL
, PRIMARY KEY (ID)
);